import {
  Utensils,
  Car,
  ShoppingBag,
  ShoppingCart,
  Film,
  Zap,
  HeartPulse,
  BookOpen,
  Home,
  Plane,
  Gift,
  Scissors,
  Repeat,
  Truck,
  DollarSign,
  TrendingUp,
  Briefcase,
  Laptop,
  Building2,
  CircleEllipsis,
  Coffee,
  Shirt,
  Gamepad2,
  Music,
  Dumbbell,
  GraduationCap,
  PawPrint,
  Wrench,
  Fuel,
  Bus,
  Wifi,
  Smartphone,
  Tv,
  CreditCard,
  Wallet,
  PiggyBank,
  Landmark,
  Receipt,
  Stethoscope,
  Pill,
  Palette,
  Camera,
  Umbrella,
  Cake,
  Bike,
  Users,
  Banknote,
  Droplet,
  Flame,
  Sparkles,
  Tag,
  Baby,
  type LucideIcon,
} from 'lucide-react';

const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  film: Film,
  zap: Zap,
  'heart-pulse': HeartPulse,
  'book-open': BookOpen,
  home: Home,
  plane: Plane,
  gift: Gift,
  scissors: Scissors,
  repeat: Repeat,
  truck: Truck,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  briefcase: Briefcase,
  laptop: Laptop,
  'building-2': Building2,
  'circle-ellipsis': CircleEllipsis,
  coffee: Coffee,
  shirt: Shirt,
  'gamepad-2': Gamepad2,
  music: Music,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  'paw-print': PawPrint,
  wrench: Wrench,
  fuel: Fuel,
  bus: Bus,
  wifi: Wifi,
  smartphone: Smartphone,
  tv: Tv,
  'credit-card': CreditCard,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  receipt: Receipt,
  stethoscope: Stethoscope,
  pill: Pill,
  palette: Palette,
  camera: Camera,
  umbrella: Umbrella,
  cake: Cake,
  bike: Bike,
  users: Users,
  banknote: Banknote,
  droplet: Droplet,
  flame: Flame,
  sparkles: Sparkles,
  tag: Tag,
  baby: Baby,
};

export const CATEGORY_ICONS = Object.keys(CATEGORY_ICON_MAP);

interface CategoryIconProps {
  icon: string;
  size?: number;
  color?: string;
}

export function CategoryIcon({ icon, size = 16, color }: CategoryIconProps) {
  const Icon = CATEGORY_ICON_MAP[icon];
  if (Icon) return <Icon size={size} style={{ color }} />;
  // Fallback: first character for unknown icons
  return <span style={{ fontSize: size * 0.8, lineHeight: 1 }}>{icon.charAt(0)}</span>;
}
