export type AccountType = 'checking' | 'savings' | 'cash' | 'credit' | 'investment' | 'wallet';
export type TransactionType = 'expense' | 'income' | 'transfer';
export type CategoryType = 'expense' | 'income' | 'both';
export type Theme = 'dark' | 'light' | 'system';
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';
export type BudgetPeriod = 'weekly' | 'monthly' | 'yearly';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  color: string;
  icon: string;
  /** Cache of `openingBalance + Σ(transaction deltas)`. Recomputable — never the source of truth. */
  balance: number;
  /**
   * The balance before any recorded transaction. Immutable in normal use, which is what makes
   * `balance` derivable and any drift reconcilable.
   */
  openingBalance: number;
  createdAt: string;
  creditLimit?: number;
  /**
   * ISO timestamp of when the account was closed, or absent while it is open. Archiving keeps
   * every transaction — it only removes the account from pickers and running totals.
   */
  archivedAt?: string;
}

/** An account from a backup file or pre-v5 storage, where `openingBalance` may be absent. */
export type ImportedAccount = Omit<Account, 'openingBalance'> & { openingBalance?: number };

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  accountId: string;
  toAccountId?: string;
  categoryId: string;
  date: string;
  note: string;
  labels: string[];
  createdAt: string;
  /** If this transaction was auto-generated by a recurring rule, the rule id. */
  recurringId?: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: CategoryType;
}

export interface Label {
  id: string;
  name: string;
  color: string;
}

export interface Budget {
  id: string;
  /**
   * Empty string means "overall" budget across all expense categories. Ignored when
   * `labelId` is set.
   */
  categoryId: string;
  /** When set, the budget tracks every expense carrying this label instead of a category. */
  labelId?: string;
  /** Limit in INR, per `period`. */
  amount: number;
  /** How often the limit resets. Monthly periods follow `Settings.monthStartDay`. */
  period: BudgetPeriod;
  /**
   * Carry the previous period's unspent amount (or overspend, as a debt) into this one,
   * envelope-style, instead of starting every period back at `amount`.
   */
  rollover: boolean;
  createdAt: string;
}

export interface RecurringTransaction {
  id: string;
  type: TransactionType;
  amount: number;
  accountId: string;
  /** Destination account. Required for `transfer` rules, absent otherwise. */
  toAccountId?: string;
  categoryId: string;
  note: string;
  labels: string[];
  frequency: RecurrenceFrequency;
  /** ISO date of the first occurrence (also next due if never run). */
  startDate: string;
  /** ISO date after which the rule stops generating. Absent means it runs forever. */
  endDate?: string;
  /** Stop after this many occurrences in total. Absent means unlimited. */
  maxOccurrences?: number;
  /** Occurrences generated so far, counted against `maxOccurrences`. */
  occurrenceCount: number;
  /** ISO timestamp of when the rule was paused, or absent while it is active. */
  pausedAt?: string;
  /** ISO date of the most recent auto-generated occurrence, or null. */
  lastRunDate: string | null;
  createdAt: string;
}

export interface Settings {
  theme: Theme;
  userName: string;
  /** Whether to automatically download a local backup JSON once per day. */
  autoLocalBackup: boolean;
  /**
   * Day of the month a financial month begins (1–28). Anything other than 1 shifts every
   * "this month" total and monthly budget to a salary-cycle window.
   */
  monthStartDay: number;
  /**
   * ISO timestamp of when the first-run wizard was completed or skipped. Absent means this
   * is a fresh install and the wizard should run before anything else.
   */
  onboardedAt?: string;
}

/** Sanitized backup contents accepted by `importData`. */
export interface ImportPayload {
  accounts?: ImportedAccount[];
  transactions?: Transaction[];
  categories?: Category[];
  labels?: Label[];
  budgets?: Budget[];
  recurring?: RecurringTransaction[];
  settings?: Settings;
}

export type ImportMode = 'replace' | 'merge';

export interface FinanceStore {
  accounts: Account[];
  transactions: Transaction[];
  categories: Category[];
  labels: Label[];
  budgets: Budget[];
  recurring: RecurringTransaction[];
  settings: Settings;
  isHydrated: boolean;
  /** ISO date (YYYY-MM-DD) of the last automatic local backup download, or null. */
  lastLocalBackupAt: string | null;
  setLastLocalBackupAt: (date: string) => void;

  addAccount: (account: Omit<Account, 'id' | 'createdAt' | 'openingBalance'>) => void;
  updateAccount: (id: string, updates: Partial<Omit<Account, 'id'>>) => void;
  /**
   * Close or reopen an account. Unlike `deleteAccount` this is non-destructive: transactions,
   * balances and recurring rules survive, so it is the right default for a closed bank account.
   */
  setAccountArchived: (id: string, archived: boolean) => void;
  deleteAccount: (id: string) => void;
  /**
   * Rebuild every account balance from its opening balance plus its transactions.
   * Returns how many accounts moved and the net drift that was corrected.
   */
  recomputeBalances: () => { changed: number; totalDrift: number };

  addTransaction: (transaction: Omit<Transaction, 'id' | 'createdAt'>) => string;
  updateTransaction: (id: string, updates: Partial<Omit<Transaction, 'id'>>) => void;
  /** Removes the transaction and reverses its delta. Returns the removed row so callers can undo. */
  deleteTransaction: (id: string) => Transaction | null;
  /**
   * Re-insert a previously deleted transaction verbatim — same id, same delta. Undoing a
   * delete must not mint a new id, or the row would diverge from any backup that has it.
   */
  restoreTransaction: (transaction: Transaction) => void;

  addCategory: (category: Omit<Category, 'id'>) => void;
  updateCategory: (id: string, updates: Partial<Omit<Category, 'id'>>) => void;
  deleteCategory: (id: string) => void;

  addLabel: (label: Omit<Label, 'id'>) => void;
  updateLabel: (id: string, updates: Partial<Omit<Label, 'id'>>) => void;
  deleteLabel: (id: string) => void;

  /** Adding a budget for a scope that already has one replaces it — one limit per scope. */
  addBudget: (budget: Omit<Budget, 'id' | 'createdAt'>) => void;
  updateBudget: (id: string, updates: Partial<Omit<Budget, 'id'>>) => void;
  deleteBudget: (id: string) => void;

  /**
   * Create a recurring rule. Pass `lastRunDate` to start the schedule mid-stream — that is how
   * "skip the backfill" is expressed: the rule stays aligned to its `startDate` cadence but
   * generates nothing for occurrences on or before that date.
   */
  addRecurring: (
    rule: Omit<RecurringTransaction, 'id' | 'createdAt' | 'occurrenceCount' | 'lastRunDate'> & {
      lastRunDate?: string | null;
    },
  ) => string;
  updateRecurring: (id: string, updates: Partial<Omit<RecurringTransaction, 'id'>>) => void;
  /** Pause or resume a rule without losing its schedule or history. */
  setRecurringPaused: (id: string, paused: boolean) => void;
  deleteRecurring: (id: string) => void;
  /** Generate any due transactions from recurring rules. Returns count generated. */
  processRecurring: () => number;

  updateSettings: (updates: Partial<Settings>) => void;

  resetToDefaults: () => void;
  /**
   * Apply an (already validated) backup payload. `replace` swaps each provided collection,
   * `merge` unions rows by id with incoming winning. Balances are recomputed either way.
   */
  importData: (data: ImportPayload, options?: { mode?: ImportMode }) => void;

  setHydrated: (hydrated: boolean) => void;
}
