export type AccountType = 'checking' | 'savings' | 'cash' | 'credit' | 'investment' | 'wallet';
export type TransactionType = 'expense' | 'income' | 'transfer';
export type CategoryType = 'expense' | 'income' | 'both';
export type Currency = 'USD' | 'EUR' | 'GBP' | 'INR' | 'JPY' | 'CAD' | 'AUD';
export type Theme = 'dark' | 'light' | 'system';
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  currency: Currency;
  color: string;
  icon: string;
  balance: number;
  createdAt: string;
  creditLimit?: number;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  accountId: string;
  toAccountId?: string;
  categoryId: string;
  date: string;
  note: string;
  labels: string[];
  createdAt: string;
  /** If this transaction was auto-generated by a recurring rule, the rule id. */
  recurringId?: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: CategoryType;
}

export interface Label {
  id: string;
  name: string;
  color: string;
}

export interface Budget {
  id: string;
  /** Empty string means "overall" budget across all expense categories. */
  categoryId: string;
  /** Monthly limit in the user's primary currency. */
  amount: number;
  createdAt: string;
}

export interface RecurringTransaction {
  id: string;
  type: Exclude<TransactionType, 'transfer'>;
  amount: number;
  accountId: string;
  categoryId: string;
  note: string;
  labels: string[];
  frequency: RecurrenceFrequency;
  /** ISO date of the first occurrence (also next due if never run). */
  startDate: string;
  /** ISO date of the most recent auto-generated occurrence, or null. */
  lastRunDate: string | null;
  createdAt: string;
}

export interface Settings {
  currency: Currency;
  theme: Theme;
  userName: string;
  /** Whether to automatically download a local backup JSON once per day (guests only). */
  autoLocalBackup: boolean;
}

export interface FinanceStore {
  accounts: Account[];
  transactions: Transaction[];
  categories: Category[];
  labels: Label[];
  budgets: Budget[];
  recurring: RecurringTransaction[];
  settings: Settings;
  isHydrated: boolean;
  /** ISO date (YYYY-MM-DD) of the last automatic local backup download, or null. */
  lastLocalBackupAt: string | null;
  setLastLocalBackupAt: (date: string) => void;

  addAccount: (account: Omit<Account, 'id' | 'createdAt'>) => void;
  updateAccount: (id: string, updates: Partial<Omit<Account, 'id'>>) => void;
  deleteAccount: (id: string) => void;

  addTransaction: (transaction: Omit<Transaction, 'id' | 'createdAt'>) => string;
  updateTransaction: (id: string, updates: Partial<Omit<Transaction, 'id'>>) => void;
  deleteTransaction: (id: string) => void;

  addCategory: (category: Omit<Category, 'id'>) => void;
  updateCategory: (id: string, updates: Partial<Omit<Category, 'id'>>) => void;
  deleteCategory: (id: string) => void;

  addLabel: (label: Omit<Label, 'id'>) => void;
  updateLabel: (id: string, updates: Partial<Omit<Label, 'id'>>) => void;
  deleteLabel: (id: string) => void;

  addBudget: (budget: Omit<Budget, 'id' | 'createdAt'>) => void;
  updateBudget: (id: string, updates: Partial<Omit<Budget, 'id'>>) => void;
  deleteBudget: (id: string) => void;

  addRecurring: (rule: Omit<RecurringTransaction, 'id' | 'createdAt' | 'lastRunDate'>) => void;
  updateRecurring: (id: string, updates: Partial<Omit<RecurringTransaction, 'id'>>) => void;
  deleteRecurring: (id: string) => void;
  /** Generate any due transactions from recurring rules. Returns count generated. */
  processRecurring: () => number;

  updateSettings: (updates: Partial<Settings>) => void;

  resetToDefaults: () => void;
  importData: (
    data: Partial<
      Pick<
        FinanceStore,
        'accounts' | 'transactions' | 'categories' | 'labels' | 'budgets' | 'recurring' | 'settings'
      >
    >,
  ) => void;

  setHydrated: (hydrated: boolean) => void;
}
