import {
  addDays,
  differenceInCalendarDays,
  endOfWeek,
  format,
  isSameDay,
  parseISO,
  startOfDay,
  startOfWeek,
} from 'date-fns';
import { roundMoney } from '@/store/balance';
import { futureOccurrences } from '@/store/recurring';
import { activeAccounts, transactionCategoryAmounts } from './calculations';
import { WEEK_STARTS_ON, type PeriodRange } from './period';
import type { Account, RecurringTransaction, Transaction, TransactionType } from '@/types';

/**
 * Cash-flow forecast.
 *
 * Projects *liquid* cash — open, non-credit accounts — forward from two inputs the app already
 * has: recurring rules (known amounts on known dates) and the recent per-category spending
 * average (everything else). Spending on a credit card doesn't move liquid cash on the day it
 * happens, so it only appears here when the card payment transfer does; that keeps the two
 * halves of the projection consistent rather than double-counting card spend.
 */

/** How far ahead the projection runs by default. */
export const DEFAULT_FORECAST_DAYS = 90;

/** How much history the everyday-spend average is drawn from. */
export const DEFAULT_LOOKBACK_DAYS = 90;

/** Open accounts that hold spendable cash. Credit lines are a liability, not a balance to draw down. */
export function liquidAccountIds(accounts: Account[]): Set<string> {
  return new Set(
    activeAccounts(accounts)
      .filter((a) => a.type !== 'credit')
      .map((a) => a.id),
  );
}

/** Sum of the liquid accounts' current balances — where the projection starts from. */
export function liquidBalance(accounts: Account[]): number {
  return roundMoney(
    activeAccounts(accounts)
      .filter((a) => a.type !== 'credit')
      .reduce((sum, a) => sum + a.balance, 0),
  );
}

/**
 * Signed effect on total liquid cash. A transfer between two liquid accounts nets to zero;
 * one that crosses the boundary (paying a card off, moving money into an investment) doesn't.
 */
export function liquidDelta(
  item: { type: TransactionType; amount: number; accountId: string; toAccountId?: string },
  liquid: Set<string>,
): number {
  const fromLiquid = liquid.has(item.accountId);

  if (item.type === 'expense') return fromLiquid ? -item.amount : 0;
  if (item.type === 'income') return fromLiquid ? item.amount : 0;

  const toLiquid = item.toAccountId ? liquid.has(item.toAccountId) : false;
  if (fromLiquid === toLiquid) return 0;
  return fromLiquid ? -item.amount : item.amount;
}

export interface ScheduledFlow {
  ruleId: string;
  note: string;
  categoryId: string;
  date: Date;
  type: TransactionType;
  amount: number;
  /** Signed effect on liquid cash — negative for money leaving. */
  delta: number;
}

export interface CategoryAverage {
  categoryId: string;
  dailyAverage: number;
  monthlyAverage: number;
  /** This category's share of the estimated everyday spend, 0–1. */
  share: number;
}

export interface ForecastPoint {
  date: Date;
  /** `yyyy-MM-dd` — stable key for chart rows. */
  key: string;
  /** Projected liquid balance at the end of this day. */
  balance: number;
  scheduledIn: number;
  scheduledOut: number;
  /** Everyday spend estimated from category averages. */
  estimatedOut: number;
}

export interface CashFlowForecast {
  startBalance: number;
  endBalance: number;
  /** One point per day, starting with today at the current balance. */
  points: ForecastPoint[];
  /** Every projected recurring occurrence in the window, chronologically. */
  scheduled: ScheduledFlow[];
  /** Per-category everyday spend, biggest first. */
  categoryAverages: CategoryAverage[];
  /** Estimated everyday (non-recurring) spend per day. */
  dailyEstimate: number;
  /** How many days of history the average was drawn from. */
  lookbackDays: number;
  totals: { scheduledIn: number; scheduledOut: number; estimatedOut: number };
  /** The lowest point of the projection. */
  low: { date: Date; balance: number } | null;
  /** First day the projection goes negative, if it ever does. */
  shortfallDate: Date | null;
  /** True when there is nothing to project from — no liquid accounts, no rules, no history. */
  isEmpty: boolean;
}

export interface ForecastInput {
  accounts: Account[];
  transactions: Transaction[];
  recurring: RecurringTransaction[];
  now?: Date;
  days?: number;
  lookbackDays?: number;
}

/**
 * Average everyday spend per category, per day. Transactions generated by a recurring rule are
 * left out: those are projected individually from the rules themselves, and counting them here
 * as well would bill every subscription twice.
 */
export function categoryDailyAverages(
  transactions: Transaction[],
  accounts: Account[],
  options: { now?: Date; lookbackDays?: number } = {},
): { averages: CategoryAverage[]; dailyEstimate: number; lookbackDays: number } {
  const now = options.now ?? new Date();
  const window = Math.max(1, options.lookbackDays ?? DEFAULT_LOOKBACK_DAYS);
  const liquid = liquidAccountIds(accounts);
  const from = startOfDay(addDays(now, -(window - 1)));

  const byCategory = new Map<string, number>();
  let earliest: Date | null = null;

  for (const t of transactions) {
    if (t.type !== 'expense' || t.recurringId) continue;
    if (!liquid.has(t.accountId)) continue;
    const date = parseISO(t.date);
    if (Number.isNaN(date.getTime()) || date < from || date > now) continue;

    if (!earliest || date < earliest) earliest = date;
    for (const { categoryId, amount } of transactionCategoryAmounts(t)) {
      byCategory.set(categoryId, (byCategory.get(categoryId) ?? 0) + amount);
    }
  }

  // Divide by the history that actually exists: a two-week-old install must not have its
  // spending spread across ninety days and read as a tenth of what it really is.
  const observedDays = earliest ? differenceInCalendarDays(now, earliest) + 1 : 0;
  const lookbackDays = Math.max(1, Math.min(window, observedDays));

  const total = Array.from(byCategory.values()).reduce((sum, amount) => sum + amount, 0);
  const dailyEstimate = roundMoney(total / lookbackDays);

  const averages = Array.from(byCategory, ([categoryId, amount]) => ({
    categoryId,
    dailyAverage: roundMoney(amount / lookbackDays),
    monthlyAverage: roundMoney((amount / lookbackDays) * 30),
    share: total > 0 ? amount / total : 0,
  }))
    .filter((a) => a.dailyAverage > 0)
    .sort((a, b) => b.dailyAverage - a.dailyAverage);

  return { averages, dailyEstimate, lookbackDays };
}

/** Project liquid cash forward day by day. */
export function buildCashFlowForecast(input: ForecastInput): CashFlowForecast {
  const now = input.now ?? new Date();
  const days = Math.max(1, input.days ?? DEFAULT_FORECAST_DAYS);
  const today = startOfDay(now);
  const horizon = addDays(today, days);

  const liquid = liquidAccountIds(input.accounts);
  const startBalance = liquidBalance(input.accounts);
  const { averages, dailyEstimate, lookbackDays } = categoryDailyAverages(
    input.transactions,
    input.accounts,
    { now, lookbackDays: input.lookbackDays },
  );

  const scheduled: ScheduledFlow[] = input.recurring
    .flatMap((rule) =>
      futureOccurrences(rule, now, horizon).map((date) => ({
        ruleId: rule.id,
        note: rule.note,
        categoryId: rule.categoryId,
        date,
        type: rule.type,
        amount: rule.amount,
        delta: roundMoney(liquidDelta(rule, liquid)),
      })),
    )
    // A rule posting only to a credit card or moving cash between two liquid accounts has no
    // effect on the projection, and listing it would just be noise.
    .filter((flow) => flow.delta !== 0)
    .sort((a, b) => a.date.getTime() - b.date.getTime());

  const scheduledByDay = new Map<string, ScheduledFlow[]>();
  for (const flow of scheduled) {
    const key = format(flow.date, 'yyyy-MM-dd');
    const bucket = scheduledByDay.get(key);
    if (bucket) bucket.push(flow);
    else scheduledByDay.set(key, [flow]);
  }

  const points: ForecastPoint[] = [
    {
      date: today,
      key: format(today, 'yyyy-MM-dd'),
      balance: startBalance,
      scheduledIn: 0,
      scheduledOut: 0,
      estimatedOut: 0,
    },
  ];

  let balance = startBalance;
  const totals = { scheduledIn: 0, scheduledOut: 0, estimatedOut: 0 };
  let low: { date: Date; balance: number } | null = null;
  let shortfallDate: Date | null = null;

  for (let offset = 1; offset <= days; offset += 1) {
    const date = addDays(today, offset);
    const key = format(date, 'yyyy-MM-dd');

    let scheduledIn = 0;
    let scheduledOut = 0;
    for (const flow of scheduledByDay.get(key) ?? []) {
      if (flow.delta > 0) scheduledIn = roundMoney(scheduledIn + flow.delta);
      else scheduledOut = roundMoney(scheduledOut - flow.delta);
    }

    balance = roundMoney(balance + scheduledIn - scheduledOut - dailyEstimate);
    totals.scheduledIn = roundMoney(totals.scheduledIn + scheduledIn);
    totals.scheduledOut = roundMoney(totals.scheduledOut + scheduledOut);
    totals.estimatedOut = roundMoney(totals.estimatedOut + dailyEstimate);

    points.push({ date, key, balance, scheduledIn, scheduledOut, estimatedOut: dailyEstimate });

    if (!low || balance < low.balance) low = { date, balance };
    if (shortfallDate === null && balance < 0) shortfallDate = date;
  }

  return {
    startBalance,
    endBalance: balance,
    points,
    scheduled,
    categoryAverages: averages,
    dailyEstimate,
    lookbackDays,
    totals,
    low,
    shortfallDate,
    isEmpty: liquid.size === 0 || (scheduled.length === 0 && dailyEstimate === 0),
  };
}

export interface CashFlowCalendarDay {
  date: Date;
  /** `yyyy-MM-dd` — stable key for grid cells. */
  key: string;
  /** Net scheduled effect on liquid cash this day — positive is money in. */
  netFlow: number;
  /** The individual scheduled occurrences landing on this day, chronological. */
  flows: ScheduledFlow[];
  /** False for the leading/trailing days that only exist to square off the week rows. */
  inRange: boolean;
  isToday: boolean;
}

export interface CashFlowCalendarMonth {
  /** Week rows, each exactly 7 days, Monday first. */
  weeks: CashFlowCalendarDay[][];
}

/**
 * A month grid of `scheduled` cash flow, the forward-looking counterpart to
 * `buildSpendingCalendar` — same grid shape, but each cell nets the day's *known future*
 * recurring occurrences instead of historical spend. Days outside `monthRange` are padded in
 * (and flagged `inRange: false`) so every row is a full week.
 */
export function buildCashFlowCalendarMonth(
  scheduled: ScheduledFlow[],
  monthRange: PeriodRange,
  now = new Date(),
): CashFlowCalendarMonth {
  const byDay = new Map<string, ScheduledFlow[]>();
  for (const flow of scheduled) {
    const key = format(flow.date, 'yyyy-MM-dd');
    const bucket = byDay.get(key);
    if (bucket) bucket.push(flow);
    else byDay.set(key, [flow]);
  }

  const today = startOfDay(now);
  const gridStart = startOfWeek(monthRange.start, { weekStartsOn: WEEK_STARTS_ON });
  const gridEnd = endOfWeek(monthRange.end, { weekStartsOn: WEEK_STARTS_ON });

  const weeks: CashFlowCalendarDay[][] = [];
  let week: CashFlowCalendarDay[] = [];

  for (let day = gridStart; day <= gridEnd; day = addDays(day, 1)) {
    const key = format(day, 'yyyy-MM-dd');
    const inRange = day >= monthRange.start && day <= monthRange.end;
    const flows = inRange ? (byDay.get(key) ?? []) : [];

    week.push({
      date: day,
      key,
      netFlow: roundMoney(flows.reduce((sum, f) => sum + f.delta, 0)),
      flows,
      inRange,
      isToday: isSameDay(day, today),
    });

    if (week.length === 7) {
      weeks.push(week);
      week = [];
    }
  }
  if (week.length > 0) weeks.push(week);

  return { weeks };
}
